var skills = {
	WAR: {
		bash: function() {},
		taunt: function() {},
		kick: function() {},
		demoralize: function() {}
	},
	PAL: {
		layHands: function() {},
		bash: function() {},
		taunt: function() {},
		heal: function() {},
		blessedHammer: function() {},
		smite: function() {},
		resolution: function() {},
		holyMight: function() {}
	},
	SHD: {
		harmTouch: function() {},
		bash: function() {},
		taunt: function() {},
		lifeTap: function() {},
		engulfingDarkness: function() {},
		bloodBoil: function() {},
		invokeFear: function() {},
		waveOfHorror: function() {}
	},
	RNG: {
		trueshotStrike: function() {},
		kick: function() {},
		ensnare: function() {},
		ignite: function() {},
		faerieFlame: function() {},
		carelessLightning: function() {},
		healing: function() {},
		feetLikeCat: function() {},
	},
	MNK: {
		roundhouseKick: function() {},
		mend: function() {},
		feignDeath: function() {},
		intimidation: function() {}
	},
	ROG: {
		backstab: function() {},
		evade: function() {},
		widowStrike: function() {},
		flashPowder: function() {}
	},
	DRU: {
		healing: function() {},
		starfire: function() {},
		skinLikeWood: function() {},
		driftingDeath: function() {},
		tornado: function() {},
		endureLightning: function() {},
		lightningBlast: function() {},
		chloroplast: function() {},
	},
	CLR: {
		holyMight: function() {},
		smite: function() {},
		blessedHammer: function() {},
		healing: function() {},
		resolution: function() {},
		symbolOfYentus: function() {},
		endureBleed: function() {},
		armorOfFaith: function() {},
	},
	SHM: {
		healing: function() {},
		frostRift: function() {},
		devouringPlague: function() {},
		drowsy: function() {},
		spiritOfTheBear: function() {},
		bloodRitual: function() {},
		endureCold: function() {},
		talismanOfTrogmaar: function() {},
	},
	BRD: {
		chantOfBattle: function() {},
		hymnOfRestoration: function() {},
		boastfulBellow: function() {},
		consonantChain: function() {},
		lucidLullaby: function() {},
		elementalRhythms: function() {},
		chorusOfClarity: function() {},
		sirensSong: function() {},
	},
	NEC: {
		engulfingDarkness: function() {},
		invokeDeath: function() {},
		venomBolt: function() {},
		bloodBoil: function() {},
		invokeFear: function() {},
		lifeTap: function() {},
		endurePoison: function() {},
		dyingBreath: function() {},
	},
	ENC: {
		discordantMind: function() {},
		colorShift: function() {},
		alacrity: function() {},
		dazzle: function() {},
		gaspingEmbrace: function() {},
		clarity: function() {},
		cajolingWhispers: function() {},
		mysticRune: function() {},
	},
	MAG: {
		lavaBolt: function() {},
		summonElemental: function() {},
		frozenOrb: function() {},
		elementalFury: function() {},
		psionicStorm: function() {},
		malaise: function() {},
		endureFire: function() {},
		stasisField: function() {},
	},
	WIZ: {
		iceBolt: function() {},
		arcaneMissiles: function() {},
		manaShield: function() {},
		fireball: function() {},
		viziersShielding: function() {},
		lightningStrike: function() {},
		glacialSpike: function() {},
		mirrorImages: function() {},
	},
}